### ISSUE TITLE
Migración de componente de edición de reglas

### ISSUE THREAD

**Issue by haxdai** [SemanticWebBuilder/SWB#10]
Migrar componente para eliminar el uso de applets
- [x] Seleccionar biblioteca para edición de reglas
- [x] Implementar UI front-end
- [x] Implementar funciones back-end en recurso (JSON -> XML -> JSON)
- [x] Eliminar applet en recurso
- [x] Verificar operadores de regla _Historial de página_
- [x] Internacionalizar componente

**Comment by haxdai** [comment]
@jordivs Ya quedó migrado el componente, los cambios ya están en la rama no-applets de:

* SWB
* SWBAdmin
* SWBPortal

**Comment by jordivs** [comment]
Ok, Inicio pruebas

**Comment by jordivs** [comment]
@haxdai  La condición de Historial de página no permite guardar la Regla, hay que eliminarla, de cualquier modo es una condición que se heredo de la versión 3.0 y ya no aplica.

**Comment by jordivs** [comment]
Las pruebas de las reglas se han terminado, sin ningún problema

**Comment by haxdai** [comment]
bb8b767b8c7357e192985e81849e8b8fc2848f3a elimina la condición de historial de página de la vista.
