### ISSUE TITLE
Error en reinicio de versiones de plantillas de un sitio web

### ISSUE THREAD

**Issue by jordivs** [SemanticWebBuilder/SWB#103]
Al hacer reinicio de versiones de planillas, borra todas exepto la primer versión creada aun cando la ultima versión sea la visible.

Pasos para replicar el Issue:
1.- Expandir un sitio web dentro de la administración de SWB
2.- Crear una plantilla 
3.- Agregar 3 versiones minimo a la plantilla, con un texto que las distinga dentro del editor de la plantilla.
4.- Asignar la última versión como la "Versión Actual" 
5.- Seleccionar el botón reinicio de versiones

Resultado:
Se borra la plantilla que se tenia como versión actual y solamente deja la primer versión creada.

**Comment by jafdeza** [comment]
Se corrigió servicio de copiado de archivos que afecta al reinicio de versiones https://github.com/SemanticWebBuilder/SWBBase/commit/a5a35cf8fe2b7f458e06fb83294ffc30bd3f08fe
