### ISSUE TITLE
Reglas

### ISSUE THREAD

**Issue by marthajimenez** [SemanticWebBuilder/SWB#106]
Descripción: Se crea la regla con opción Not y no tiene el comportamiento esperado.
Procedimiento:

Se crea una regla con las opciones de "El usuario esté firmado", "sea igual a", "Si"  y se selecciona la opción Not, enseguida se asocia a una sección.

Vista de configuración:
![4](https://user-images.githubusercontent.com/8809489/59636332-dcbb0f00-9118-11e9-9749-2c822300682f.png)

* Al visualizar la sección en el portal la regla no se aplica correctamente.

Vista de la sección:
![5](https://user-images.githubusercontent.com/8809489/59636333-dd53a580-9118-11e9-9378-2c041dec0389.png)

**Comment by jafdeza** [comment]
@marthajimenez Se corrigió armado del XML y se agregó a la evaluación del NOT
https://github.com/SemanticWebBuilder/SWBPortal/commit/6f4b48684a6e5fe9919cef0ff23c1f847b0c75f0
https://github.com/SemanticWebBuilder/SWBModel/commit/b3974301636f1b53fa407c6f51a6fbe1c836deb4

**Comment by marthajimenez** [comment]
@jafdeza Se valida la solución al Bug.
