### ISSUE TITLE
Reinicio de plantillas

### ISSUE THREAD

**Issue by marthajimenez** [SemanticWebBuilder/SWB#110]
Precondiciones
Existe un administrador superusuario de la herramienta SWBPortal.
Existe una plantilla llamada home con 2 versiones.

Procedimiento
El administrador superusuario crea una nueva versión de la plantilla y la activa como versión actual. 

<img width="562" alt="22" src="https://user-images.githubusercontent.com/8809489/59638124-2e659880-911d-11e9-9122-8455667f2c8d.png">

El administrador superusuario edita y guarda la información de la plantilla. 

<img width="541" alt="21" src="https://user-images.githubusercontent.com/8809489/59638123-2e659880-911d-11e9-9d71-91f170d6f584.png">

El administrador superusuario selecciona la opción Reinicio de Versiones. 

<img width="564" alt="24" src="https://user-images.githubusercontent.com/8809489/59638126-2e659880-911d-11e9-8ffe-28ff06094ba8.png">

Al revisar la plantilla se observa que no contiene la información de la ultima versión de las plantillas.

<img width="545" alt="23" src="https://user-images.githubusercontent.com/8809489/59638125-2e659880-911d-11e9-8cc3-b71b87f23665.png">

**Comment by jafdeza** [comment]
Se corrigió servicio de copiado de archivos que afecta al reinicio de versiones https://github.com/SemanticWebBuilder/SWBPortal/commit/6d9bc2f4389ea92f2300e90fa2e5c4c895797036

**Comment by marthajimenez** [comment]
@jafdeza Se probaron los cambios en un nuevo ambiente y al iniciar el servidor de aplicaciones se encontraron los errores almacenados en el archivo Log_Errores_Tomcat.txt. 
[Log_Errores_Tomcat.txt](https://github.com/SemanticWebBuilder/SWB/files/3315089/Log_Errores_Tomcat.txt)

Se procedió a reiniciar el servidor de aplicaciones, levantando sin problemas. Al probar la funcionalidad se encontraron los errores almacenados en el archivo Log_Errores_Plantilla
[Log_Errores_Plantilla.txt](https://github.com/SemanticWebBuilder/SWB/files/3315094/Log_Errores_Plantilla.txt)


La prueba consistió en reiniciar las versiones sin embargo se observa que mantiene la primera versión de la plantilla.

**Comment by haxdai** [comment]
@jafdeza Se adjuntan logs con líneas reajustadas.
[Log_Errores_Plantilla.txt](https://github.com/SemanticWebBuilder/SWB/files/3316014/Log_Errores_Plantilla.txt)
[Log_Errores_Tomcat.txt](https://github.com/SemanticWebBuilder/SWB/files/3316015/Log_Errores_Tomcat.txt)

**Comment by jafdeza** [comment]
@marthajimenez  @haxdai  Se dejo el SWBUtils como estaba y se modificó el recurso. De los errores recibidos posiblemente sean falta de permisos. Al hacer  pruebas de funcionamiento no he podido replicar el error. En mis pruebas después de la corrección no me marcó ningún error. Se subieron nuevas versiones del SWBUtils y de SWBATemplateEdit para que validen.
https://github.com/SemanticWebBuilder/SWBPortal/commit/8387be76864b95bbd448957ff335b2815e0366c6
https://github.com/SemanticWebBuilder/SWBBase/commit/b1bae405edad416095fb3e1188755f77277a775e

**Comment by marthajimenez** [comment]
@jafdeza Al probar los cambios se observa que las plantillas mantienen la versión inicial, esto es debido a que no se eliminan las carpetas en el FileSystem. A continuación se describe el procedimiento para realizar la prueba.

Se crea una plantilla, se edita con el texto "Primera version", se crea una segunda versión, se edita con el texto "Primera version segunda version" y **se asigna como actual**, se crea una _tercer versión a partir de la segunda_ y se edita con el texto "Primera version segunda version, tercer version" y **se asigna como actual**. 

<img width="866" alt="1" src="https://user-images.githubusercontent.com/8809489/60219688-0838aa80-9839-11e9-848b-60735f1d72bd.png">

Al reiniciar las versiones en la vista de la plantilla se eliminan de forma adecuada.

<img width="866" alt="2" src="https://user-images.githubusercontent.com/8809489/60219689-0838aa80-9839-11e9-904b-3f7a1a38b044.png">

Sin embargo en FileSystem no se eliminan las versiones y se mantiene la plantilla original

<img width="428" alt="3" src="https://user-images.githubusercontent.com/8809489/60219690-08d14100-9839-11e9-8ef8-a9ffdbc4ec93.png">

<img width="416" alt="4" src="https://user-images.githubusercontent.com/8809489/60219691-08d14100-9839-11e9-99d0-6be53fd5374b.png">
