### ISSUE TITLE
Filtros de administración

### ISSUE THREAD

**Issue by marthajimenez** [SemanticWebBuilder/SWB#111]
Descripción 
Se requiere que un usuario pueda tener acceso a la papelera de reciclaje, bitácora, propiedades y relacionados de un sitio, dicho usuario deberá tener acceso solo a ciertas funcionalidades del árbol en la administración. Derivado de estas restricciones se crea un filtro de administración y se asigna a dicho usuario, sin embargo las pestañas requeridas no son mostradas.

Precondiciones

Existe un administrador superusuario de la herramienta SWBPortal
Existe un usuario administrador que será restringido.
Existe un sitio o  portal.

Procedimiento
El administrador superusuario crea un filtro de administración y asigna las opciones para la pestaña Filtros sobre sitios: Plantillas, Reglas, Lenguajes, DNS, Componentes de Estrategia, Componentes de Sistema, Componentes de Contenido, Repositorio de Usuarios y Páginas Web.
 
![FiltroSobreSitios](https://user-images.githubusercontent.com/8809489/59641305-af755d80-9126-11e9-8691-73edfad120af.png)

El administrador superusuario elige en la pestaña Configuración de Vista las siguientes alternativas: Editar Versión, Relacionados, Bitácora, Propiedades, Reglas, Editar Plantilla, Filtro de Secciones, Instancias, Información, Configuración, Administrar, Contenidos, Periodos, Papelera de Reciclaje, Editar Periodo.

![papelera_de_reciclaje__propiedades__bitacora](https://user-images.githubusercontent.com/8809489/59641307-af755d80-9126-11e9-942f-3357c13d4f13.png)

El administrador superusuario guarda la información del filtro.
El administrador superusuario asigna el filtro al usuario administrador que será restringido. 

![usuario_filtro](https://user-images.githubusercontent.com/8809489/59641308-b00df400-9126-11e9-99b8-ed157ae5489d.png)

El usuario administrador que será restringido se loguea a la herramienta SWBPortal, enseguida da clic al sitio, en la vista que se muestra no aparecen las pestañas de Papelera de Reciclaje, Relacionados, Bitácora, Propiedades. 

![vistaFiltroPapelera](https://user-images.githubusercontent.com/8809489/59641309-b00df400-9126-11e9-8628-42dab51522d0.png)

**Comment by jafdeza** [comment]
Se agregó validación para soporte a WebSite el pintado de pestañas que existen en el filtro de administración.
https://github.com/SemanticWebBuilder/SWB/commit/42e7af08330e93989638b40103797f2c87b8ef9d
