### ISSUE TITLE
gitignore for eclipse

### ISSUE THREAD

**Issue by jordivs** [SemanticWebBuilder/SWB#20]
_From @haxdai on January 26, 2017 19:11_

Al trabajar con eclipse se generan las carpetas .classpath, .project y .settings. Sería bueno agregarlas al gitignore para evitar que se suban por error.

_Copied from original issue: SemanticWebBuilder/SWBPortal#67_

**Comment by haxdai** [comment]
Se han agregado líneas para ignorar estas rutas en los proyectos
