### ISSUE TITLE
Implementación de UTF-8 encoding  para las Plantillas

### ISSUE THREAD

**Issue by jordivs** [SemanticWebBuilder/SWB#24]
_From @jordivs on March 24, 2017 23:54_

Implica que en las instancias de producción tengan que actualizar cada plantilla del sitio para actualizar los cambios. https://github.com/SemanticWebBuilder/SWBPortal/commit/34f886f4a1ba145c2a9d9f2f83557aa468da2e69
¿Proponen alguna solución? para que no sea complicado para los usuarios que cuenten con varias plantillas en sus instancias.

_Copied from original issue: SemanticWebBuilder/SWBPortal#83_

**Comment by jordivs** [comment]
_From @haxdai on April 14, 2017 0:49_

@jordivs cómo te fue con las pruebas?

**Comment by jordivs** [comment]
Se levantó una instancia con las siguientes características:

**Instancia de Pruebas:**
OS: Centos 7
AS: Jetty
DB: Hipersonyc
JDK: 1.8

Se modificó el archivo **start.sh** en la variable **JAVA_OPTS** el valor **-Dfile.encoding=UTF-8** 
Se importó el sitio de documentación
Se realizó el cambio del charset de la plantilla  "Documentación" **charset=utf-8**

**Resultado**

Las palabras acentuadas de los títulos de página se muestran un carácter diferente.
El texto del contenido en HTMLContent se muestra correctamente las palabras acentuadas.

**Comment by haxdai** [comment]
@jordivs @softjei Todo esto:

https://github.com/search?q=org%3ASemanticWebBuilder+%22iso-8859-1%22&type=Code&utf8=%E2%9C%93

y esto

https://github.com/search?utf8=%E2%9C%93&q=org%3ASemanticWebBuilder+%22iso8859-1%22&type=Code

forza el uso de ISO-8859-1

**Comment by jordivs** [comment]
Se dejo la codificación ISO-8859
