### ISSUE TITLE
Sustituir DWR con FileUpload de Apache commons

### ISSUE THREAD

**Issue by haxdai** [SemanticWebBuilder/SWB#30]
### Propuesta
Hacer refactor de los servlets de carga de archivos para utilizar Apache commons FileUpload en lugar de DWR.

### Razonamiento
Al parecer, DWR se utiliza en SemanticWebBuilder sólo para la carga de archivos y monitoreo de subida en form elements y algunos recursos. Sin embargo, no se utilizan las características adicionales de la biblioteca. La carga y monitoreo se puede implementar con apache commons, que ya es una dependencia de la aplicación.

### Posibles beneficios
Se elimina una dependencia a biblioteca de terceros, del mismo modo, se estandariza la carga de archivos en todos los recursos (varios usan ya apache commons).

### Qué hay que hacer

- [ ] Definir servicio de carga de archivos y monitoreo de subida
- [ ] Refactor de servlet fileupload para usar apache commons
- [ ] Definir patrón para notificación de progreso y carga en clientes (observer? push notifications con websockets?)
- [ ] Refactor de recursos y form-elements que utilicen DWR

**Comment by jordivs** [comment]
¿Cómo vez la propuesta? @softjei

**Comment by jordivs** [comment]
No procede
