### ISSUE TITLE
SWB no inicia: no hay driver de mysql

### ISSUE THREAD

**Issue by haxdai** [SemanticWebBuilder/SWB#33]
Al clonar el proyecto y generar el WAR, la biblioteca de mysql-connector no existe en WEB-IN/lib por lo que al iniciar la aplicación, no se puede establecer conexión a la base de datos.

**Comment by jordivs** [comment]
En el repo de Bundle solo se agregaron las bibliotecas necesarias para realizar las pruebas por el momento, pero le comento a @softjei que agregue las librerias de los conectores faltantes

**Comment by jordivs** [comment]
Se integrará el conector en la versión liberada, también revisará cual de la siguientes librerías se tienen que incluir en esta versión
- [ ] bigdata-1.0.1.jar
- [ ] ChatServer
- [ ] Chiva
- [ ]  Chva-web
- [ ] cmu_time_awb
- [ ] cmu_us_kal
- [ ]  cmudict04
- [ ] cmulex
- [ ]  colt
- [ ] concurret
- [ ] ctc_utils-5-4-2005
- [ ]  cweb-extser
- [ ] dsi-utils-1.6.020610
- [ ] en_us
- [ ]  facebook-java-api-3.0.0-SNAPSHOT.jar
- [ ]  facebook-java-api-schema-3.0.0-SNAPSHOT.jar
- [ ]  fastutil-5.1.5.jar
- [ ]  groovy-all-1.6.3.jar
- [ ]  high-scale-lib-v1.1.2.jar
- [ ]  iri-0.8.jar
- [ ] iText-rtf-2.1.5.jar
- [ ]  iText-2.1.5.jar
- [ ] jaxen-core.jar
- [ ] jaxen-jdom.jar
- [x] jena-2.6.3.jar
- [ ]  jxl.jar
- [ ]  jython.jar
- [ ]  lgpl-utils-1.0.6-020610.jar
- [ ]  mail-1.3.3.jar
- [ ]  openrdf-sesame-2.3.0-onejar.jar
- [ ]  quercus.jar
- [ ]  resin-util.jar
- [ ]  saxon-dom-8.7.jar
- [ ] saxpath.jar
- [ ]  serializer.jar
- [ ]  spring.jar
- [ ]  twitter4j-2.0.9.jar
- [ ]  virt_jena.jar
- [ ] virtjdbc3.jar

**Comment by haxdai** [comment]
@jordivs voy a mover lo de las librerías a otro issue

**Comment by jordivs** [comment]
Se incluyo el driver de mysql y se quedaron las librerias necesarias
