### ISSUE TITLE
Minificar HTML procesado de las plantillas

### ISSUE THREAD

**Issue by haxdai** [SemanticWebBuilder/SWB#35]
### Propuesta
Minificar el HTML de las plantillas que se entrega al cliente. Puede ser una opción configurable por plantilla o para todo el sitio.

### Razonamiento
Aunque la compresión por parte del servidor de aplicaciones ayuda a reducir los tiempos de carga de las páginas, quitar algunos KB de peso al HTML entregado tras el procesamiento de las plantillas podría ayudar a mejorar el rendimiento.

### Consideraciones
Deben hacerse pruebas de performance para saber si el trade-off entre el tiempo de procesamiento en minificar el HTML y el tiempo de sólo comprimir la salida a través del servidor de aplicaciones no es equivalente. En tal caso, daría lo mismo minificar o no.

**Comment by jordivs** [comment]
Se realizó pruebas de performance y se puede reducir en tamaño con la compresión de los siguientes scripts

   /swbadmin/js/dojo/dojo/dojo.js  102.3KiB (65% reduction).
  /swbadmin/js/swb.js  39.9KiB (77% reduction).
  /swbadmin/js/dojo/dojo/parser.js  6.0KiB (59% reduction).
  /swbadmin/js/dojo/dojo/date/stamp.js  900B (48% reduction).
 /swbadmin/js/dojo/dojo/_base/url.js  884B (50% reduction).
 /swbadmin/js/dojo/dojo/promise/all.js  368B (40% reduction).

Cuando SWB resuelve una página con plantilla blanca, la procesa en 5 ms, y entre más peticiones, la resuelve hasta en 1 ms. claro que esto puede variar dependiendo el HTML que se va a entregar.
Y como funcionalidad de SWB se cuenta con una configuración de en páginas web y en componentes del cache que acelera los puntos que pudiera deteriorar el desempeño y uno que se aplica es el  cache por página y por usuario, para más información  [http://semanticwebbuilder.org.mx/es/DocumentacionSWB/Configuracion_de_recrsos_-_Tipo_de_Cache](url)

Se puede considerar la reducción de estos scripts

**Comment by jordivs** [comment]
La plantilla se pasa comprimida, se checará si conviene minificar aun más

**Comment by jordivs** [comment]
La información ya se manda comprimida
