### ISSUE TITLE
"Agregar Recurso" No muestra el listado de recursos en la edición de la plantilla

### ISSUE THREAD

**Issue by jordivs** [SemanticWebBuilder/SWB#36]
_From @jordivs on March 16, 2017 0:38_

"Agregar Recurso" No muestra el listado de recursos
![2017-03-15_183936](https://cloud.githubusercontent.com/assets/7914633/23976598/649480e0-09ae-11e7-8499-2c9b43fb80c3.jpg)

_Copied from original issue: SemanticWebBuilder/SWBPortal#75_

**Comment by jordivs** [comment]
_From @haxdai on March 16, 2017 2:6_

@jordivs Algún error en la consola de JavaScript? Con algún navegador en específico?

**Comment by jordivs** [comment]
@haxdai Pasa en FireFox 52.0.0 y en Google Chrome  56.0.2924.87 
La instancia tiene las siguientes caracteristicas:
Sistema Operativo: CentOS 7
Base de Datos: Hipersonic
Servidor de Aplicaciones: Tomcat-9.0.0M17

**Comment by jordivs** [comment]
_From @haxdai on March 16, 2017 22:21_

@jordivs En Windows, Ubuntu Linux y Mac funciona OK. Reviso CentOS, no te faltará bajar cambios de SWB o SWBAdmin o SWBPortal?

![firefox52](https://cloud.githubusercontent.com/assets/7064389/24020937/03838cfe-0a64-11e7-8e2b-900e742e83d1.png)


![chrome56](https://cloud.githubusercontent.com/assets/7064389/24021021/6e5dbef0-0a64-11e7-84ff-66982acd3312.png)

**Comment by jordivs** [comment]
_From @haxdai on March 16, 2017 23:5_

![centos7firefox](https://cloud.githubusercontent.com/assets/7064389/24022176/7db3ac38-0a6a-11e7-8be5-ba770be44bc9.png)

![centos7chrome](https://cloud.githubusercontent.com/assets/7064389/24022219/b95d93ac-0a6a-11e7-95f0-2ea7406e11dd.png)

**Comment by jordivs** [comment]
Se vuelve a presentar el issue, en Fireox 53.0.3 (32-bit) y en GoogleChrome Versión 58.0.3029.110 (64-bit), tambien se probo en Internet Explorer 11 y Edge @haxdai

**Comment by jordivs** [comment]
Pudiste replicar este issue @haxdai

**Comment by haxdai** [comment]
Listo @jordivs

**Comment by jordivs** [comment]
Perfecto!!!
