### ISSUE TITLE
La clase del recurso SWBForum no se encuentra 

### ISSUE THREAD

**Issue by jordivs** [SemanticWebBuilder/SWB#43]
La clase del recurso de Forum, no se encuentra
![2017-06-15_115210](https://user-images.githubusercontent.com/7914633/27196979-30af20fc-51d2-11e7-9d87-a093d7319f02.png)

Mensaje: 	org.semanticwb.portal.api.SWBResourceException: Class Name:class org.semanticwb.portal.resources.sem.forum.SWBForum not found...
Fecha: 	Thu Jun 15 13:52:23 CDT 2017
Stack trace: 	

Thu Jun 15 13:52:23 CDT 2017: Class Name:class org.semanticwb.portal.resources.sem.forum.SWBForum not found...
// org.semanticwb.portal.api.SWBResourceException: Class Name:class org.semanticwb.portal.resources.sem.forum.SWBForum not found...
// org.semanticwb.portal.api.GenericSemResource.getSemanticObject(GenericSemResource.java:200)
// org.apache.jsp.swbadmin.jsp.objectTab_jsp._jspService(objectTab_jsp.java:246)
// org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
// javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
// org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443)
// org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
// org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
// javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
// org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
// org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
// org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
// org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
// org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
// org.semanticwb.servlet.SWBVirtualHostFilter.doFilter(SWBVirtualHostFilter.java:349)
// org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
// org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
// org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
// org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
// org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:475)
// org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
// org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
// org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
// org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
// org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
// org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:498)
// org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
// org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:796)
// org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1368)
// org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
// java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
// java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
// org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
// java.lang.Thread.run(Thread.java:745)

**Comment by haxdai** [comment]
Caused by #71
