### ISSUE TITLE
Revisar estilos en recursos de administración

### ISSUE THREAD

**Issue by haxdai** [SemanticWebBuilder/SWB#47]
El cambio de estilo en la administración (cambios al tema soria de dojo) afectan a recursos de la administración que utilizan dojo.

Ejemplo: 

<img width="943" alt="captura de pantalla 2017-06-22 a la s 12 37 44" src="https://user-images.githubusercontent.com/7064389/27447698-a93f46a8-5747-11e7-8050-7764014cddf6.png">

Habría que:
- [x] Revisar uno a uno los recursos de la administración para identificar issues
- [ ] Modificar la vista de los recursos de administración afectados

**Comment by jordivs** [comment]
En los siguientes recursos afecta el cambio de estilo #52
