### ISSUE TITLE
Quitar contenido de prueba en sitio básico

### ISSUE THREAD

**Issue by haxdai** [SemanticWebBuilder/SWB#48]
El sitio básico tiene contenido de prueba que hay que eliminar.

Ejemplos:

<img width="190" alt="captura de pantalla 2017-06-22 a la s 12 43 55" src="https://user-images.githubusercontent.com/7064389/27447946-8be922a8-5748-11e7-8f68-bc745df6ce0b.png">

<img width="213" alt="captura de pantalla 2017-06-22 a la s 12 44 53" src="https://user-images.githubusercontent.com/7064389/27447977-a39f88e2-5748-11e7-8d2f-becd70e628dc.png">

<img width="210" alt="captura de pantalla 2017-06-22 a la s 12 46 27" src="https://user-images.githubusercontent.com/7064389/27448036-d725de78-5748-11e7-99b5-bca2641e5d04.png">

**Comment by haxdai** [comment]
@jajs1975

**Comment by jordivs** [comment]
@haxdai Ya limpié el sitio y quite todos los recursos innecesarios, genere un basic.zip para poder cargarlo a la administración @softjei
