### ISSUE TITLE
Se pueden cargar archivos de cualquier tipo en creación de plantillas

### ISSUE THREAD

**Issue by haxdai** [SemanticWebBuilder/SWB#5]
El applet de edición de plantillas permite la carga de cualquier tipo de archivo, este archivo se despacha en la vista previa sin restricción.

|Precondiciones|Postcondiciones|Version afectada|
|---|---|---|
|Se cuenta con una plantilla creada para un sitio en la administración de SWB|Se despachan archivos arbitrariamente en vista previa de la plantilla, no se requiere que el usuario pertenezca al grupo de _SuperUsuario_|Hasta 4.5.11.2

### Procedimiento para reproducir el issue:
1. Acceder a la pestaña _Editar Plantilla_ de la plantilla deseada
2. En el listado de versiones hacer click en el botón _Editar_
3. En el editor de plantillas hacer click en la opción _Abrir de archivo_
<img width="874" alt="captura de pantalla 2017-02-22 a la s 13 18 00" src="https://cloud.githubusercontent.com/assets/7064389/23228446/27039a8e-f902-11e6-85f7-e304f9bb9611.png">

4. En la ventana de selección ubicar un archivo distinto al formato HTML, puede ser un .exe
<img width="576" alt="captura de pantalla 2017-02-22 a la s 13 20 08" src="https://cloud.githubusercontent.com/assets/7064389/23228466/34f97064-f902-11e6-9be8-b67b39c3eb5b.png">

5. Confirmar la carga de la plantilla
<img width="520" alt="captura de pantalla 2017-02-22 a la s 13 20 16" src="https://cloud.githubusercontent.com/assets/7064389/23228478/430d6c32-f902-11e6-8fee-c1420c1bd707.png">

### Resultado
El editor de plantillas muestra el código binario del archivo cargado
<img width="882" alt="captura de pantalla 2017-02-22 a la s 13 20 30" src="https://cloud.githubusercontent.com/assets/7064389/23228486/4ae8b4de-f902-11e6-821e-c98cc28f8ff9.png">

En la lista de versiones, el hacer click sobre el botón _Vista previa_ genera la descarga del archivo
<img width="840" alt="captura de pantalla 2017-02-22 a la s 13 20 44" src="https://cloud.githubusercontent.com/assets/7064389/23228494/5245aab6-f902-11e6-8efb-3d39d5772cb7.png">

**Comment by haxdai** [comment]
Con la migración al editor Web se invalida el issue

**Comment by jordivs** [comment]
Perfecto!!!
