### ISSUE TITLE
Link "SWB Portal" de la Plantilla login.html esta incorrecto 

### ISSUE THREAD

**Issue by jordivs** [SemanticWebBuilder/SWB#50]
![2017-06-22_170102](https://user-images.githubusercontent.com/7914633/27457977-50471902-576c-11e7-9fa8-3c73e8cf472e.png)

**Comment by haxdai** [comment]
@jajs1975

**Comment by jordivs** [comment]
se corrige con el commit 8ca665f98f2b5c5c1bb997b56c518ffc010e9db4
