### ISSUE TITLE
No se crea el recurso blog

### ISSUE THREAD

**Issue by jordivs** [SemanticWebBuilder/SWB#51]
pasos para replicar la incidencia:

1.- Crear un recurso blog
2.- En la administración, definir un nombre al blog
3.- Seleccionar el botón Crear blog

Resultado:
Se muetsra un error 500 y se genera el siguiente error en la consola
![2017-06-26_175718](https://user-images.githubusercontent.com/7914633/27563708-d4545d16-5a98-11e7-935f-f8cabcfb00b4.png)

Mensaje: 	java.lang.NullPointerException
Fecha: 	Mon Jun 26 17:45:03 CDT 2017
Stack trace: 	

Mon Jun 26 17:45:03 CDT 2017: null
// java.lang.NullPointerException
// org.semanticwb.platform.SemanticModel.getCounter(SemanticModel.java:887)
// org.semanticwb.portal.resources.sem.blog.base.BlogBase$ClassMgr.createBlog(BlogBase.java:88)
// org.semanticwb.portal.resources.sem.blog.SWBBlog.createBlog(SWBBlog.java:1350)
// org.semanticwb.portal.resources.sem.blog.SWBBlog.processAction(SWBBlog.java:1861)
// org.semanticwb.servlet.internal.Distributor._doProcess(Distributor.java:376)
// org.semanticwb.servlet.internal.Distributor.doProcess(Distributor.java:101)
// org.semanticwb.servlet.SWBVirtualHostFilter.processInternalServlet(SWBVirtualHostFilter.java:405)
// org.semanticwb.servlet.SWBVirtualHostFilter.doFilter(SWBVirtualHostFilter.java:332)
// org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
// org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
// org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
// org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
// org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:475)
// org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
// org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
// org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
// org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
// org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
// org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:498)
// org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
// org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:796)
// org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1368)
// org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
// java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
// java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
// org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
// java.lang.Thread.run(Thread.java:745)

**Comment by haxdai** [comment]
Caused by #71

**Comment by jordivs** [comment]
Resolved by #71
