### ISSUE TITLE
Se muestra toda la estructura de documentos del servidor en el editor de plantillas

### ISSUE THREAD

**Issue by jordivs** [SemanticWebBuilder/SWB#54]
Dentro del editor de plantillas al abrir documentos del servidor, se muestra toda la estrutura de FileSystem, cuando se debe de mostrar solamente el directorio de la plantilla. El usuario cuenta con permisos de Super Usuario

Pasos para replicar la incidencia
1.- Entrar al editor de plantillas de un sitio
2.- Seleccionar "Explorador de archivos"

Resultado:

Se muestra todo el sistema de archivos desde el editor de plantillas.
![captura](https://user-images.githubusercontent.com/7914633/27806290-41700416-5fff-11e7-9ce8-ff6790e4c36f.PNG)

**Comment by JRedentor** [comment]
Zafo Jordis!!!! :)

¿Puedes agregar a la descripción del bug, el código fuente de la ventana de navegador que muestra la interface del explorador de archivos, por favor @jordivs ?

Saludos.

**Comment by jordivs** [comment]
Listo !!! @JRedentor Código fuente 

````html
<html>
  <head>
    <meta charset="utf-8">
    <title>Explorador de archivos</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=2" />
    <link rel="stylesheet" type="text/css" href="/swbadmin/js/elfinder/css/jquery-ui.css">
    <script src="/swbadmin/js/elfinder/js/jquery.min.js"></script>
    <script src="/swbadmin/js/elfinder/js/jquery-ui.min.js"></script>
    <link rel="stylesheet" type="text/css" href="/swbadmin/js/elfinder/css/elfinder.min.css">
    <link rel="stylesheet" type="text/css" href="/swbadmin/js/elfinder/css/theme.css">
    <script src="/swbadmin/js/elfinder/js/elfinder.min.js"></script>
    <script type="text/javascript" charset="utf-8">
    	let $fileExplorer_Nuevo_1;
    	let  $window = $(window);

      $(document).ready(function() {
        $fileExplorer_Nuevo_1 = $('#elfinder_Nuevo_1').elfinder({
          url : '/elFinderConnector',  // connector URL (REQUIRED)
          resizable: true,
          height: $window.height(),
          resourceId : '51',
          resourcePath : '/models/SWBAdmin/Resource/51',
          customData : {site : 'Nuevo', template:'1', version: '2'}
        });
      });

			$window.resize(function() {
     		var win_height = $window.height();
     		if( $("#elfinder_Nuevo_1").height() != win_height ){
           $fileExplorer_Nuevo_1 && $fileExplorer_Nuevo_1.resize('auto',win_height);
     		}
 			});

 			window.addEventListener("unload", function() {
 				let win = window.opener;
 				if (win && !win.closed) {
 					win.toggleBrowserButton_Nuevo_1(true);
 				}
 			});
    </script>
    <style type="text/css">
    	body {
    		margin: 0px;
    	}

    	#elfinder_Nuevo_1 {
    		width: 100%;
    		min-width: 100%;
    		height: 100% !important;
    	}

    	.ui-resizable-handle { display:none !important; }

    	.elfinder-navbar-dir, .elfinder-button-search input {
    		outline: 0;
    	}
    </style>
  </head>
  <body>
    <div id="elfinder_Nuevo_1"></div>
  </body>
</html>
````

**Comment by JRedentor** [comment]
@jordivs!!!
Por favor, revisa si la clase SWBConnectorServlet del jar de elFinder en tu instancia, tiene fecha del 30/03/2017. La clase la encuentras en la ruta cn\bluejoe\elfinder\servlet dentro del jar! Y me avisas qué encuentras, por favor!
Saludos.

**Comment by jordivs** [comment]
@JRedentor La clase tiene fecha de 21/06/2016 :(

**Comment by JRedentor** [comment]
Nooo!!! @jordivs!!! Pues hay que generar el war con la versión de la rama dev, en el proyecto SWBExternalDeps. Por favor, actualicen el jar, eso debe estar generando el problema y muy seguramente también lo del #60!!!

**Comment by jordivs** [comment]
Noooo!!! @JRedentor !!! Mejor agrega en el POM de SWBBundle el SWBExternalDeps, para que no tenga estos problemas -_-

**Comment by JRedentor** [comment]
Noooo!!! @jordivs!!! Porque supongo que por algo lo dejaron como está!!! Solo actualiza el jar para que no tengas esos problemas!!!

**Comment by haxdai** [comment]
@jordivs @JRedentor hay un clon de elfinder-servlet en la organización. Podemos hacer ahí las adecuaciones al código de elfinder y probar, esto después de liberar versión, sugiero.

@jordivs, en el caso del repositorio externaldeps, voy a mover los cambios de dev a master.

**Comment by haxdai** [comment]
@jordivs ya está lo de dev en master para externaldeps

**Comment by JRedentor** [comment]
Suena muy bien! Aunque, como dices @haxdai, esto tendrá que esperar hasta después de liberar versión, ya que implica revisar el código del clon, compararlo con lo que se tiene y hacer los ajustes necesarios! Por lo que no sería viable en este momento @jordivs .

**Comment by jordivs** [comment]
Gracias @haxdai, la instancia ya cuenta con elfindes actualizado y ya no se muestra todo el filesystem, aunque la incidencia #60 si se sigue presentado @JRedentor
