### ISSUE TITLE
DB Consultas despliega un applet

### ISSUE THREAD

**Issue by jordivs** [SemanticWebBuilder/SWB#56]
- [x] Cambiar el applet de DB Consultas que despliega las tablas de laase de datos a otra tecnología 

![captura](https://user-images.githubusercontent.com/7914633/27843412-c789385e-60d8-11e7-883b-2ac6d37cee62.PNG)

**Comment by haxdai** [comment]
@softjei @jordivs @JRedentor @jafdeza Sí lo tomo, pero no puedo tomarlo con prioridad alta. Si urge, podrían asignarlo a alguien más.

**Comment by jordivs** [comment]
Gracias @haxdai lo reviso con @jajs1975

**Comment by haxdai** [comment]
@jordivs @softjei Así se verá ahora el recurso, están de acuerdo?

<img width="957" alt="captura de pantalla 2017-07-07 a la s 14 29 26" src="https://user-images.githubusercontent.com/7064389/27973786-e6a5d75c-6320-11e7-8edf-855839f087c7.png">

**Comment by jordivs** [comment]
A mi me parece bien

**Comment by haxdai** [comment]
@softjei @jordivs Ya quedó migrado el recurso, listo para pruebas. Ya no me pases más talachas de @jajs1975 :stuck_out_tongue:.

**Comment by jordivs** [comment]
Pruebas Listo!!!
