### ISSUE TITLE
Filtro de secciones tiene conflicto con el estilo

### ISSUE THREAD

**Issue by jordivs** [SemanticWebBuilder/SWB#58]
El filtro de secciones genera un conflicto con el estilo soria.css y ocasiona que no se muestre correctamente.

**Pasos para replicar la incidencia:**
1.- En el menú principal Usuarios/Filtros/Filtros de secciones.
2.- Seleccionar el repositorio a filtrar y dar clic en "Editar filtro"

**Resultado**:

No se muestra el desplegado de los usuarios y los filtros

![captura](https://user-images.githubusercontent.com/7914633/27844092-4d6ed240-60e2-11e7-9ceb-f07d764b126a.PNG)

**Comment by haxdai** [comment]
No aplica ya que se hizo revert de los cambios al estilo
