### ISSUE TITLE
Flujo de publicación no se construye correctamente la ventana de Agregar secuencia

### ISSUE THREAD

**Issue by jordivs** [SemanticWebBuilder/SWB#59]
La ventana de "Agregar secuencia", no despliega el combo de "Enviar a otra actividad"

Pasos para replicar la incidencia

1.- En la edición del flujo de publicación, agregar 2 actividades
2.- Seleccionar "Agregar secuencia"

Resultado:

En la sección de "Enviar a otra actividad", no se muestra el combo de las actividades que se generaron.

![captura](https://user-images.githubusercontent.com/7914633/27844467-e6edf0a4-60e7-11e7-9ebf-5b77785b6434.PNG)

**Comment by haxdai** [comment]
@jordivs @softjei Hay que hacer revert de los cambios de estilo a soria, que afectarán también a recursos de portal que lo usen.

**Comment by jordivs** [comment]
@softjei Estoy de acuerdo con @haxdai  de hacer una liberación sin applets a mas tardar el viernes, y la siguiente semana dedicarnos a ver afectaciones con el nuevo diseño.  @jajs1975

**Comment by jordivs** [comment]
con el rollback ya no se genera el error
