### ISSUE TITLE
Explorador de archivos desde plantillas genera carpeta en webapps

### ISSUE THREAD

**Issue by haxdai** [SemanticWebBuilder/SWB#60]
## Descripción
Al editar una plantilla y abrir el explorador de archivos, se genera una carpeta en webapps con la ruta al directorio del template. Esto provoca que se haga un deploy en el servidor de aplicaciones con esa carpeta.

## Cómo reproducir
1. Ingresar a la administración de SWB y editar una plantilla.
2. En el editor, presionar el botón del explorador de archivos <img width="24" alt="captura de pantalla 2017-07-05 a la s 15 17 16" src="https://user-images.githubusercontent.com/7064389/27883118-079bb932-6195-11e7-8273-a70d331c3823.png">
3. Se abre la ventana del explorador en la ruta del template
![captura de pantalla 2017-07-05 a la s 15 18 16](https://user-images.githubusercontent.com/7064389/27883145-28fc9f42-6195-11e7-8821-03f71c7a4ad4.png)
4. Se genera una carpeta en webapps del servidor de aplicaciones con la ruta al directorio del template
<img width="477" alt="captura de pantalla 2017-07-05 a la s 15 19 16" src="https://user-images.githubusercontent.com/7064389/27883181-4a5317ca-6195-11e7-846d-6aae290e89e2.png">
5. Se despliega una aplicación con esa ruta en el servidor
<img width="1139" alt="captura de pantalla 2017-07-05 a la s 15 19 57" src="https://user-images.githubusercontent.com/7064389/27883210-63ff387a-6195-11e7-855e-314a848c4099.png">

## Entorno
Servidor de aplicaciones tomcat 9
Oracle JDK 1.8.0_65
Sistema operativo macOS Sierra

**Comment by JRedentor** [comment]
@jordivs, ya está actualizado el jar de elFinder en la rama dev de SWBExternalDeps con la corrección correspondiente a este issue!

**Comment by jordivs** [comment]
había una ruta que se estaba formando mal, que Windows si interpretaba bien, pero no en Unix, y provocaba que se creará una carpeta con ese nombre tan largo. Se la forma en que se armaba la ruta de la carpeta https://github.com/SemanticWebBuilder/SWBExternalDeps/commit/9c6e0c8ea7a187f58c278e74b97156c88e0dedff
