### ISSUE TITLE
Nuevas páginas en config no tienen tag SWBSECURITY

### ISSUE THREAD

**Issue by haxdai** [SemanticWebBuilder/SWB#61]
Las nuevas páginas login.html 403.html password.html no tienen el tag &lt;SWBSECURITY&gt;
Cuando quede activada la opción de encriptar datos de login, no funcionarán.

@jajs1975

**Comment by jordivs** [comment]
Se agregó el tag **<SWBSECURITY>** a las plantillas login.html, 403.html,  password.html commit 8ca665f98f2b5c5c1bb997b56c518ffc010e9db4
