### ISSUE TITLE
Diálogo de inicio de sesión en sitio de administración no funciona cuando está habilitada la encriptación de datos

### ISSUE THREAD

**Issue by haxdai** [SemanticWebBuilder/SWB#62]
## Descripción
Al habilitar la opción **login/encryptData** del archivo security.properties, el diálogo de inicio de sesión de la administración de Semantic deja de funcionar.

## Cómo reproducir
1. Detener el servidor de aplicaciones
2. Habilitar la opción **login/encryptData** del archivo security.properties
3. Iniciar el servidor de aplicaciones
4. Iniciar sesión en el sitio de administración (tab1)
5. Abrir otro tab en el navegador (tab2)
6. En tab2 entrar también al sitio de administración
7. Cerrar sesión en tab2
8. En tab1 hacer click en el icono de un sitio para que se muestre el diálogo de iniciar sesión
9. Se muestra el diálogo y falla el inicio al introducir los datos

<img width="360" alt="captura de pantalla 2017-07-07 a la s 09 37 58" src="https://user-images.githubusercontent.com/7064389/27962602-0707a346-62f8-11e7-9366-708d6941dd58.png">

**Comment by haxdai** [comment]
Relacionado con #53

**Comment by jordivs** [comment]
No permite iniciar sesión siguiendo los pasos de la incidencia.
