### ISSUE TITLE
Po qué no se cargan URLs en HTTPS?

### ISSUE THREAD

**Issue by haxdai** [SemanticWebBuilder/SWB#63]
## Descripción
Cuando se configura SemanticWebBuilder tras un servidor proxy que gestiona las peticiones por HTTPS, varias llamadas por AJAX en la administración y otros componentes generan un comportamiento erróneo, pues el servidor bloquea peticiones http.

![captura de pantalla 2017-07-13 a la s 11 03 42](https://user-images.githubusercontent.com/7064389/28176037-95828588-67bb-11e7-8822-6e61eeb81a68.png)

## Posible causa
Es probable que algunos recursos utilicen URLs construidas prefijando el protocolo http.

## Posibles soluciones
* Construir URLs en los recursos con los métodos apropiados, sin prefijar el protocolo

**Comment by haxdai** [comment]
La solución para esto es mediante configuración de los servidores. Para evitar el bloqueo de iframes hay que configurar en el proxy el header de respuesta <code>X-Frame-Options: SAMEORIGIN</code> y en tomcat, agregar la configuración del proxy en el objeto Connector, por ejemplo:

````xml
<Connector port="8080" protocol="HTTP/1.1"
  connectionTimeout="20000"
  redirectPort="8443"
  proxyName="mi.dominio.com"
  proxyPort="443"
  scheme="https"
/>
````

**Comment by jordivs** [comment]
@jajs1975

**Comment by jordivs** [comment]
@jordisvs  Documentar
