### ISSUE TITLE
Una instancia con contexto no encuentra las rutas 

### ISSUE THREAD

**Issue by jordivs** [SemanticWebBuilder/SWB#64]
En a instancia con contexto no carga los siguientes recursos

- [x] Plantillas de config, loginhtml, 500.html, password.html @softjei  @haxdai 
- [x] Vista de documentos del servidor desde la plantilla @haxdai @JRedentor 
- [x] Vista de Filtro de Secciones @haxdai

**Comment by haxdai** [comment]
@jordivs 

El primer punto tiene que ver con a) Las llamadas a recursos en las páginas de error y b) cómo se escriben los scripts en el tag SWBSECURITY, no tengo nada que ver :P.

<img width="891" alt="captura de pantalla 2017-07-19 a la s 16 52 29" src="https://user-images.githubusercontent.com/7064389/28391259-e5bf90cc-6ca2-11e7-8221-401e990c7b8b.png">

**Comment by haxdai** [comment]
@jordivs No pude reproducir el tercer caso. Tienes más detalle?

<img width="1093" alt="captura de pantalla 2017-07-19 a la s 18 04 19" src="https://user-images.githubusercontent.com/7064389/28393501-b418ca98-6cac-11e7-9849-e2a722712c0f.png">

**Comment by jordivs** [comment]
Ok, ya vi el problema, es otro, cuando se crea un usuario en cualquier repositorio se rompe la plantilla. levantaré otro issue

**Comment by JRedentor** [comment]
@jordivs , zafo?!?!? 
Para el segundo punto, en el javascript (código fuente del HTML) que construye la interfaz de elFinder, se incluye la ruta del contexto??

**Comment by jordivs** [comment]
@haxdai me pordrías apoyar con lo que comenta @JRedentor

**Comment by haxdai** [comment]
@jordivs @JRedentor el segundo punto está palomeado y atendido desde ayer.

**Comment by JRedentor** [comment]
:O :O :O
