### ISSUE TITLE
Agregar constructor privado a ClassMgr en generador de código

### ISSUE THREAD

**Issue by haxdai** [SemanticWebBuilder/SWB#67]
Agregar un constructor privado en la generación del código de la clase estática ClassMgr de cada clase semántica.

- [ ] Modificar CodeGenerator.java en SWBPlatform

https://sonarqube.hasdaipacheco.com/coding_rules#rule_key=squid%3AS1118

**Comment by haxdai** [comment]
Puede afectar el motor de ejecución de SWBProcess

**Comment by jordivs** [comment]
No aplica
