### ISSUE TITLE
Explicitar funcionamiento de componente Wiki

### ISSUE THREAD

**Issue by haxdai** [SemanticWebBuilder/SWB#69]
En la edición de una entrada en el componente wiki (org.semanticwb.portal.resources.wiki.Wiki), los usuarios esperan que al presionar el botón para agregar una imagen, el componente presente un diálogo para cargarla, sin embargo, sólo inserta el TAG para colocar la imagen.

**Comment by jordivs** [comment]
El wiki de SWBPortal no cuenta con la funcionalidad de upload, para visualizar una imagen se requiere llamar de una ruta física, ya sea interna o externa. Por ejemplo
![captura](https://user-images.githubusercontent.com/7914633/29940261-48d234bc-8e54-11e7-9364-d48033590a3b.PNG)
![captura](https://user-images.githubusercontent.com/7914633/29940315-6a72f886-8e54-11e7-910b-b22ff43b2795.PNG)

- [ ] Se propone como mejora implementar un wiki mejorado
